language: php
sudo: false
addons:
  apt:
    packages:
      - parallel
cache:
  directories:
    - $HOME/.composer/cache

# Do not build feature branches or alpha/beta releases
branches:
  only:
    - master
    - develop
    - /^([0-9]+\.){1,2}(x|[0-9]+)$/

# This is executed for all stages
before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - composer require nimut/typo3-complete="$TYPO3_VERSION"
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

# Configure build stages (with build matrix above, test stage is implicitly defined)
jobs:
  fast_finish: true
  include:
    - stage: test
      php: 7.3
      env: TYPO3_VERSION=^9.5
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^9.5
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^7.6.1
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^7.6.1
    - stage: 🚢 to ter
      if: tag IS present
      php: 7.0
      before_install: skip
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            # Install requirements
            composer require --dev helhum/ter-client dev-master
            # Cleanup before we upload
            git reset --hard HEAD && git clean -fx

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            .Build/bin/ter-client upload easydb . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
