# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2017
  project: easydb TYPO3 integration (Deutsch)
  version: 1.0
  release: 1.0.0
  latex_documents:
  - - Index
    - easydb.tex
    - easydb TYPO3 integration
    - Helmut Hummel
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
